// LFB Portal — Week-Ahead Digest + Day-Before Reminders
// Two modes, one function:
//   (no params)      → Sunday 3 PM MT: the full week ahead, to Jake + Victoria
//   ?mode=tomorrow   → daily 3 PM MT: what's happening tomorrow, with
//                      type-specific subjects ("your bake starts tomorrow",
//                      "you're shipping X tomorrow", "you have a delivery")
// Items marked done in the portal calendar send NO day-before reminder,
// and show crossed out in the Sunday digest.
// Recipients: DIGEST_RECIPIENTS secret (comma-separated).

import { createClient } from "npm:@supabase/supabase-js@2";
const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
const RECIPIENTS = (Deno.env.get("DIGEST_RECIPIENTS") ?? "info@lazarfamilybakehouse.com").split(",").map(s => s.trim()).filter(Boolean);
const FROM_EMAIL = Deno.env.get("DIGEST_FROM") ?? "orders@lazarfamilybakehouse.com";
const GB_SUMMARY: Record<string, string> = { "grandma-jeanne-sampler": "Grandma Jeanne's Sampler - each box: 1 bag Chocolate-Chip, 1 Almond, 1 Funfetti, 1 Gluten-Free CC + 2 Mandel Bread two-packs + thank-you card", "the-shabbat-mandelbites-box": "Shabbat Box - each box: 2 bags Chocolate-Chip, 1 Almond, 1 Gluten-Free CC + thank-you card", "mandelbites-pick-your-mix-6-pack": "Pick Your Mix 6-Pack - 6 bags in the MIX THE CUSTOMER CHOSE (check the Goldbelly order slip!)", "treat-the-office": "Treat the Office - 24 little pouches of Chocolate-Chip Mandel Bread (2 pieces each)", "bakehouse-tour": "Bakehouse Tour - 2 bags of EVERY flavor (8 bags total) + thank-you card" };
const DOW = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
function mtToday(): Date { const now = new Date(new Date().toLocaleString("en-US", { timeZone: "America/Denver" })); now.setHours(12,0,0,0); return now; }
function dstr(d: Date): string { return d.getFullYear() + "-" + String(d.getMonth()+1).padStart(2,"0") + "-" + String(d.getDate()).padStart(2,"0"); }
function pretty(ds: string): string { const p = ds.split("-").map(Number); const dt = new Date(p[0], p[1]-1, p[2]); return DOW[dt.getDay()] + ", " + dt.toLocaleDateString("en-US",{month:"short",day:"numeric"}); }
function projectAO(ao: any, dates: string[]): string[] { const dow = DOW.indexOf(ao.day); if (dow < 0) return []; const startD = ao.start_date ? new Date(ao.start_date + "T12:00:00") : null; return dates.filter(ds => { const p = ds.split("-").map(Number); const dt = new Date(p[0], p[1]-1, p[2], 12); if (dt.getDay() !== dow) return false; if (startD && dt < startD) return false; if (ao.freq === "Weekly") return true; if (ao.freq === "Bi-Weekly") { const anchor = startD ?? dt; return Math.round((dt.getTime() - anchor.getTime()) / (7*864e5)) % 2 === 0; } const nth = startD ? Math.ceil(startD.getDate()/7) : 1; return Math.ceil(p[2]/7) === nth; }); }
Deno.serve(async (req) => {
const mode = new URL(req.url).searchParams.get("mode") ?? "week";
const sb = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const base = mtToday(); if (mode === "tomorrow") base.setDate(base.getDate() + 1);
const span = mode === "tomorrow" ? 1 : 7;
const dates: string[] = []; for (let i = 0; i < span; i++) { const d = new Date(base); d.setDate(base.getDate() + i); dates.push(dstr(d)); }
const d0 = dates[0]; const dl = dates[dates.length - 1];
const { data: orders } = await sb.from("orders").select("id, invoice_num, retailer_id, delivery_date, status, total, order_items(product, qty)").gte("delivery_date", d0).lte("delivery_date", dl).neq("status", "Pending");
const { data: retailers } = await sb.from("retailers").select("id, name");
const rName = new Map((retailers ?? []).map((r: any) => [r.id, r.name]));
const { data: events } = await sb.from("calendar_events").select("*").gte("event_date", d0).lte("event_date", dl);
const { data: aos } = await sb.from("auto_orders").select("*").eq("active", true);
const byDay = new Map<string, { sort: number; html: string }[]>();
const add = (ds: string, sort: number, html: string) => { if (!byDay.has(ds)) byDay.set(ds, []); byDay.get(ds)!.push({ sort, html }); };
for (const o of orders ?? []) { const what = (o.order_items ?? []).map((i: any) => i.qty + "x " + i.product).join(", "); add(o.delivery_date, 1, "<strong>📦 Deliver to " + (rName.get(o.retailer_id) ?? "?") + "</strong> - INV-" + String(o.invoice_num).padStart(4, "0") + " - $" + Number(o.total).toFixed(2) + (what ? "<br><span style='color:#7a6a58;font-size:13px;'>What is in it: " + what + "</span>" : "")); }
for (const e of events ?? []) { if (e.done && mode === "tomorrow") continue; const dp = e.done ? "✓ <span style='text-decoration:line-through;opacity:.6;'>" : ""; const dsx = e.done ? "</span>" : ""; if (e.type === "gb_ship") { const s = GB_SUMMARY[e.package_key ?? ""] ?? e.title ?? "Goldbelly package"; const q = e.qty ?? 1; add(e.event_date, 0, dp + "<strong style='color:#c0392b;'>🚚 SHIP GOLDBELLY: " + q + " box" + (q > 1 ? "es" : "") + "</strong><br><span style='color:#7a6a58;font-size:13px;'>" + s + (q > 1 ? " - ship " + q + " of these" : "") + "</span>" + (e.title ? "<br><span style='color:#7a6a58;font-size:13px;'>📝 " + e.title + "</span>" : "") + dsx); } else if (e.type === "bake") { add(e.event_date, 2, dp + "<strong style='color:#8b6914;'>🍞 Bake day</strong>" + (e.title ? " - " + e.title : "") + dsx); } else if (e.type === "media") { add(e.event_date, 3, dp + "<strong style='color:#7b5ea7;'>📸 Media</strong>" + (e.title ? " - " + e.title : "") + dsx); } else if (e.type === "prospect") { add(e.event_date, 3, dp + "<strong style='color:#1f7a72;'>🤝 Potential partner drop/ship</strong>" + (e.title ? " - " + e.title : "") + dsx); } else { add(e.event_date, 3, dp + "📝 " + (e.title || "Note") + dsx); } }
for (const ao of aos ?? []) { for (const ds of projectAO(ao, dates)) { const what = (ao.products ?? []).map((p: any) => p.qty + "x " + p.product).join(", "); add(ds, 4, "<em style='color:#8a7a68;'>🔄 " + ao.retailer_name + " auto-order due (" + ao.freq + ")</em>" + (what ? "<br><span style='color:#7a6a58;font-size:13px;'>Usual order: " + what + " - open the portal to create it</span>" : "")); } }
let daysHtml = ""; let total = 0;
for (const ds of dates) { const items = (byDay.get(ds) ?? []).sort((a, b) => a.sort - b.sort); total += items.length; daysHtml += "<tr><td style='padding:10px 14px;border-bottom:1px solid #e4d8c8;vertical-align:top;white-space:nowrap;'><strong>" + pretty(ds) + "</strong></td><td style='padding:10px 14px;border-bottom:1px solid #e4d8c8;'>" + (items.length ? items.map(i => "<div style='margin:4px 0;'>" + i.html + "</div>").join("") : "<span style='color:#b0a08c;'>Nothing scheduled</span>") + "</td></tr>"; }
if (mode === "tomorrow" && total === 0) { return new Response(JSON.stringify({ skipped: "nothing scheduled tomorrow" }), { headers: { "Content-Type": "application/json" } }); }
const its = byDay.get(d0) ?? []; const nGb = its.filter(i => i.sort === 0).length; const nDel = its.filter(i => i.sort === 1).length; const nBake = its.filter(i => i.sort === 2).length;
let heading = "🗓 The Week Ahead"; let sub = "🗓 Week Ahead: " + total + " item" + (total === 1 ? "" : "s") + " - " + pretty(d0); if (mode === "tomorrow") { const parts: string[] = []; if (nBake) parts.push(nBake === 1 ? "a bake" : nBake + " bakes"); if (nGb) parts.push(nGb === 1 ? "a Goldbelly shipment" : nGb + " Goldbelly shipments"); if (nDel) parts.push(nDel === 1 ? "a delivery" : nDel + " deliveries"); if (nBake && !nGb && !nDel) { heading = "🍞 Your bake starts tomorrow"; sub = "Reminder: your bake starts tomorrow (" + pretty(d0) + ")"; } else if (nGb && !nBake && !nDel) { const pkgs = (events ?? []).filter((e: any) => e.type === "gb_ship" && e.event_date === d0 && !e.done).map((e: any) => (e.qty ?? 1) + "x " + ((GB_SUMMARY[e.package_key ?? ""] ?? "package").split(" - ")[0])).join(", "); heading = "🚚 Shipping tomorrow"; sub = "Reminder: you're shipping " + pkgs + " tomorrow - what's included is below"; } else if (nDel && !nBake && !nGb) { heading = "📦 Delivering tomorrow"; sub = nDel === 1 ? "Reminder: you have a delivery tomorrow" : "Reminder: you have " + nDel + " deliveries tomorrow"; } else if (parts.length) { heading = "⏰ Tomorrow at the bakehouse"; sub = "Reminder for tomorrow: " + parts.join(", "); } else { heading = "⏰ Tomorrow"; sub = "Reminder: " + total + " item" + (total === 1 ? "" : "s") + " scheduled tomorrow"; } }
const html = "<div style='font-family:Georgia,serif;max-width:640px;margin:0 auto;background:#fdf6ee;padding:24px;border-radius:12px;'><h2 style='color:#2d1b0e;margin:0 0 4px;'>" + heading + "</h2><p style='color:#7a6a58;margin:0 0 16px;'>" + pretty(d0) + (span > 1 ? " through " + pretty(dl) : "") + " - " + total + " item" + (total === 1 ? "" : "s") + " scheduled</p><table style='width:100%;border-collapse:collapse;background:#fff;border-radius:8px;overflow:hidden;'>" + daysHtml + "</table><p style='color:#b0a08c;font-size:12px;margin-top:16px;'>Sent automatically by the LFB Partner Portal calendar.</p></div>";
const res = await fetch("https://api.resend.com/emails", { method: "POST", headers: { Authorization: "Bearer " + RESEND_API_KEY, "Content-Type": "application/json" }, body: JSON.stringify({ from: "Lazar Family Bakehouse <" + FROM_EMAIL + ">", to: RECIPIENTS, subject: sub, html: html }) });
const out = await res.json();
return new Response(JSON.stringify({ mode: mode, sent_to: RECIPIENTS, items: total, resend: out }), { headers: { "Content-Type": "application/json" } });
});
